# Application Settings
spring.application.name=demo
server.port=9000

# Database Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/local_db
spring.datasource.username=root
spring.datasource.password=myp@ssw0rd
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

